### PR TITLE
Shift away from suggesting heaven

### PR DESCRIPTION
**Pull request by atmos**
A bunch of the development over the last few months has been around handling organization hooks, two factor auth, and custom(private) provider support. So there's a bunch of cool stuff you can do now that previous required heaven. This should document and give examples for some advanced usage.

### CODE REVIEW

**Comment by willdurand** [comment]
Hey @atmos, does that mean Heaven is not needed anymore? I'm using Slack + hubot/hubot-deploy + heaven + Fabric on private servers, should I get rid of heaven?

**Comment by atmos** [comment]
@willdurand Nope. I think I'm going to remove notifiers from heaven and probably have stuff like fabric and capistrano stay in it. I think for less complicated deployments it's unnecessary.

**Comment by atmos** [comment]
Also, heaven will have less logic around workflows and act like more of a task dispatcher.

**Comment by willdurand** [comment]
@atmos I see, thank you. Does it mean that hubot(-deploy) will handle notifications itself?

Our hubot is not accessible from the outside, and I like that. It was not needed since Slack talked to hubot (`/deploy`), hubot to GitHub (create deployment events), GH to heaven (receive deployment events), and heaven to Slack (notifications):

    .-> Slack -> hubot -> GitHub -> Heaven -.
    |_______________________________________|

As far as I understand, Heaven will still receive deployment events and perform the tasks, but it won't send notifications anymore. At least, it will send notifications back to hubot(-deploy), right?

**Comment by atmos** [comment]
So, it's up to you now. The `github_deployment_status_event` deployment event is optional to handle in hubot itself, but there's some boilerplate if you don't want to host a heaven for yourself unless you need it. Handling deployment status events in hubot has the downside of often times missing the deployment success event on deploying itself because it's restarting.

There is an issue with the way heaven is handling notifications now on slack and I think we need to find some consistency around deployment user ids. Previously we were using usernames from slack(where i was testing most) and now I'm sending the actual id(handles hipchat weirdness which I'm using now). We need to have heaven handle user id lookups or store usernames in the payload. 

All of your points are valid and in line w/ the way I was architecting things before I started trying to make everything work with hipchat. Once I get our heroku stuff sorted I'm hoping to go back and make things work for slack again.

**Comment by willdurand** [comment]
Hi @atmos, I am 100% available to give a hand on this. (My main use case is: slack + non-heroku deployments)

**Comment by atmos** [comment]
@willdurand If you want to update heaven to work with something `deployment.userName` instead of `deployment.user` like in [this pr](https://github.com/atmos/hubot-deploy/pull/101) is proposing.

It'll require updating the notifiers in heaven to work with the new format and use that for displaying the name instead of the id. For historical purposes I think preserving the slack id, hipchat jid, etc is more worth preserving.

**Comment by willdurand** [comment]
@atmos should I rely on `userName` for Slack notifier only or all by default? Here is a commit that uses `userName` if available, or default to `user` so no BC break involved I'd say: https://github.com/TailorDev/heaven/commit/645958181eb3ac7a6393b5b63fadb78e083d5c2a.

**Pull request merged**
