### PR TITLE
Fix slack user name

### PR DESCRIPTION
**Pull request by dlackty**
This should fix second issue of #59.

The following is the response of `hubot who am i` using Slack:

```
id: U024ZEPMY
name: dlackty
real_name: Richard Lee
email_address: REDACTED
slack: [object Object]
reply_to: C024ZUJH7
room: web
githubLogin: dlackty
vault: [object Object]
@dlackty: You are known as dlackty on GitHub
```

### CODE REVIEW

**Comment by shaneog** [comment]
Confirmed working (for me)

**Comment by atmos** [comment]
I would prefer that we update the reading username to something like `deployment.userName` instead of `deployment.user`.

It'll require updating the notifiers in heaven to work with the new format and use that for displaying the name instead of the id. For historical purposes I think the slack id, hipchat jid, etc is worth preserving.

**Comment by atmos** [comment]
@dlackty Are you using this with a heaven install for chat notifications?

**Comment by shaneog** [comment]
@atmos I know it wasn't directed at me, but I am using this branch with a heaven install and Slack notifications.

**Comment by dlackty** [comment]
@atmos Yes, we're using it with heaven for chat notifications.

**Comment by atmos** [comment]
@dlackty @shaneog Can you try with hubot-deploy 0.13.10 and heaven@master? I kept the id but added a `user_name` parameter that should notifier properly from heaven.

**Comment by dlackty** [comment]
@atmos I tired and it worked! Thanks for your help. :+1:

**Comment by shaneog** [comment]
@atmos Looks like it's working for me too :+1:  Thanks!

**Pull request merged**
